### ISSUE TITLE
Erro ao utlizar Mixins de Media Queries

### ISSUE THREAD

**Issue by igorcunhabr** [evvvrado/pumpkinplate#1]
Amigo, parabéns pela estrutura, estava testando mais encontrei dificuldades em utilizar o mixin de Media Queries, fiz da seguinte forma:

`import { media } from "@/styles/Mixins";

${media.sm_phone} {
     background-color: red;
}`

porem não obtive sucesso, qual seria a forma correta de utilizar???

**Comment by evvvrado** [comment]
Olá, @igorcunhabr! Obrigado por criar a Issue e utilizar o repositório.

Então, o problema é que "media" é uma função e no seu código ela está sendo utilizada como objeto. Não lembro exatamente o motivo de ter feito dessa forma na época, haha. Mas, a aplicação correta seria assim:

```
@media ${media("sm_phone")} {
      background-color: red;
}
```

Qualquer dúvida estou a disposição!

**Comment by igorcunhabr** [comment]
Obrigado Amigo! uma atualização para next 14 cairia bem, belo projeto!
